services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: datasphere360_customer_ecommerce_v2
    ports:
      - "5551:5432"
