orders = [["ORD001", "Laptop", 75000, "Completed"], ["ORD002", "Mouse", 500, "Completed"],
          ["ORD003", "Laptop", 75000, "Returned"],
          ["ORD004", "Keyboard", 1500, "Completed"], ["ORD005", "Laptop", 75000, "Completed"],
          ["ORD006", "Monitor", 20000, "Fraud"], ["ORD0016", "Plasma", 20000, "Fraud"],
          ["ORD007", "Mouse", 500, "Completed"], ["ORD008", "Laptop", 75000, "Completed"],
          ["ORD008", "Laptop", 75000, "Completed"], ["ORD008", "Laptop", 75000, "Completed"],
          ["ORD008", "Laptop", 75000, "Completed"], ["ORD008", "Laptop", 75000, "Completed"]]

print(
    f"\n Display All Orders Using a nested loop, print the entire order table row by row so that each order’s details are displayed clearly.")
print('=' * 140)
for items in orders:
    for i in items:
        print(f"  {i:<15}", end='|')
    print()

print(
    f"\n Detect Suspicious Activity The system suspects fraud when: the same product appears more than 3 times, OR an order has status Fraud")
print('-' * 140)

for items in orders:
    if orders.count(items) >= 3:
        print("❌ Suspicious Activity has been detected : Level 1")
        for i in items:
            if i == "Fraud":
                print("❌ Suspicious Activity has been detected: LEVEL 2 ")

print('-' * 140)
print(
    "\n Calculate Total Revenue Only Completed orders contribute to revenue. Write code that: iterates through the dataset adds the price of all completed orders prints the total revenue generated for the day.")

total_revenue = 0
for item in orders:
    if item[3] == "Completed":
        total_revenue = total_revenue + item[2]
print(f" the total revenue of Completed orders is {total_revenue}")

print('*' * 140)
print("\n Count Order Types Using loops and conditional statements, count how many orders fall into each category")

orders_fall_Completed = 0
orders_fall_Fraud = 0
orders_fall_Returned = 0

for items in orders:
    if items[3] == "Completed":
        orders_fall_Completed += orders.count(orders[3])
    elif items[3] == "Fraud":
        orders_fall_Fraud += orders.count(orders[3])
    else:
        orders_fall_Returned += orders.count(orders[3])
print(orders_fall_Completed, "Completed ")
print(orders_fall_Fraud, "Fraud")
print(orders_fall_Returned, "Returned")

print("=" * 140)
print("\n Generate a List of Unique Products. Create a new list containing unique product names present in the dataset. You must implement this without using the set() function.")

# unique_prod = []
# for items in orders:
#     if orders.count(items[1])==1:
#         print(items)


# unique_prod_names = []
# for items in orders:
#     if items[1] == "Laptop" or items[1] == "Mouse" or items[1] == "Plasma" or items[1] == "Keyboard" or items[1] == "Monitor":
#         if items[1] not in unique_prod_names:
#             unique_prod_names.append(items[1])
# print(f"\n The final list with unique product name is  :  {unique_prod_names}")




unique_prod_names = [] # new list for getting the unique product name
for items in orders: # i loop in the list of lists
    if items[1] == "Laptop" or items[1] == "Mouse" or items[1] == "Plasma" or items[1] == "Keyboard" or items[1] == "Monitor": # Item [1] because its my index where there are all my products names
        try:
            if items[1] not in unique_prod_names: # i first make sure that they are not on the list created above
                unique_prod_names.append(items[1]) # i just add if the is the name is maching
            else:
                pass
        except Exception as e:
            print(e)


print(f"\n The final list with unique product name is  :  {unique_prod_names}")

print(
    "\nProduct Sales Analysis For each unique product, determine: how many times it was ordered total revenue generated by that product This requires nested loops.")

print("=" * 140)
oders_time_Laptop = 0
ordered_total_revenue_Laptop = 0

oders_time_Keyboard = 0
ordered_total_revenue_Keyboard = 0

oders_time_Monitor = 0
ordered_total_revenue_Monitor = 0

oders_time_Mouse = 0
ordered_total_revenue_Mouse = 0

oders_time_Plasma = 0
ordered_total_revenue_Plasma = 0

for items in orders:
    if items[1] == "Laptop":
        oders_time_Laptop = oders_time_Laptop + orders.count(orders[1])
        ordered_total_revenue_Laptop = ordered_total_revenue_Laptop + items[2]

    if items[1] == "Keyboard":
        oders_time_Keyboard = oders_time_Keyboard + orders.count(orders[1])
        ordered_total_revenue_Keyboard = ordered_total_revenue_Keyboard + items[2]

    if items[1] == "Monitor":
        oders_time_Monitor = oders_time_Monitor + orders.count(orders[1])
        ordered_total_revenue_Monitor = ordered_total_revenue_Monitor + items[2]

    if items[1] == "Mouse":
        oders_time_Mouse = oders_time_Mouse + orders.count(orders[1])
        ordered_total_revenue_Mouse = ordered_total_revenue_Mouse + items[2]

    if items[1] == "Plasma":
        oders_time_Plasma = oders_time_Plasma + orders.count(orders[1])
        ordered_total_revenue_Plasma = ordered_total_revenue_Plasma + items[2]

print("ordered time Laptop: ", oders_time_Laptop)
print("total revenu Laptop: ", ordered_total_revenue_Laptop)
print('-' * 140)
print("ordered time Keyboard: ", oders_time_Keyboard)
print("total revenu Keyboard: ", ordered_total_revenue_Keyboard)
print('-' * 140)
print("ordered time Monitor: ", oders_time_Monitor)
print("total revenu Monitor: ", ordered_total_revenue_Monitor)
print('-' * 140)
print("ordered time Mouse: ", oders_time_Mouse)
print("total revenu Mouse: ", ordered_total_revenue_Mouse)
print('-' * 140)
print("ordered time Plasma: ", oders_time_Plasma)
print("total revenu Plasma: ", ordered_total_revenue_Plasma)





print('=' * 140)
print("\n Identify the Most Sold Product Based on the frequency of orders, determine which product appears the most in the dataset.")

"""on going """
# print("\n")
# print("\n")
# most_solded_items = []
# for items in orders:
#     if items[3] == "Completed":
#         if items[1] not in most_solded_items:
#             most_solded_items.append(items[1])
#         print("ok")
# print(most_solded_items)


print('=' * 140)
print('\n Remove Fraud Orders Create a cleaned dataset by removing orders whose status is "Fraud". Use list methods to store the cleaned data in a new list.')
